server:
  port: 8866

sync:
  interval: 24h

repos:
  - name: "kewuuuu-cyber-psychiatrist"
    url:  "https://gitcode.com/kewuuuu/Cyber_Psychiatrist"
    sync: "https://gitcode.com/kewuuuu/Cyber_Psychiatrist"
    lfs: true

  - name: "zhanyang1-xuanzhe"
    url: "https://gitcode.com/zhanyang1/xuanzhe"
    sync: "https://gitcode.com/zhanyang1/xuanzhe"

  - name: "xiongbingfu-first-game"
    url: "https://gitcode.com/xiongbingfu/First-game"
    sync: "https://gitcode.com/xiongbingfu/First-game"

  - name: "lweex999-bailuxianhua"
    url: "https://github.com/lweex999/bailuxianhua"
    sync: "https://gh-proxy.com/https://github.com/lweex999/bailuxianhua"

  - name: "haiyangxing4521-haiyangxing"
    url: "https://gitcode.com/haiyangxing4521/haiyangxing"
    sync: "https://gitcode.com/haiyangxing4521/haiyangxing"

  - name: "richardjiang213-dorabirdy"
    url: "https://gitcode.com/richardjiang213/dorabirdy"
    sync: "https://gitcode.com/richardjiang213/dorabirdy"

  - name: "dora-example"
    url:  "https://gitcode.com/ippclub/dora-example"
    sync: "https://gitcode.com/ippclub/dora-example"

  - name: "dora-demo"
    url:  "https://gitcode.com/ippclub/dora-demo"
    sync: "https://gitcode.com/ippclub/dora-demo"

  - name: "dora-story"
    url:  "https://gitcode.com/ippclub/dora-story"
    sync: "https://gitcode.com/ippclub/dora-story"

  - name: "lsd"
    url:  "https://gitcode.com/ippclub/lsd"
    sync: "https://gitcode.com/ippclub/lsd"

  - name: "lsd-spine-1x"
    url:  "https://gitcode.com/ippclub/lsd-spine-1x"
    sync: "https://gitcode.com/ippclub/lsd-spine-1x"
    lfs: true

  - name: "lsd-spine-2x"
    url:  "https://gitcode.com/ippclub/lsd-spine-2x"
    sync: "https://gitcode.com/ippclub/lsd-spine-2x"
    lfs: true

storage:
  path: ./data

download:
  base_url: http://localhost:8866

rate_limit:
  rps: 10
  burst: 20

log:
  level: info
  filename: ./logs/dora-osg.log
  max_size: 10    # megabytes
  max_backups: 10  # number of backups
  max_age: 30      # days
  compress: true   # compress rotated files
